### PR TITLE
Correcting version with -rv

### PR DESCRIPTION
**Pull request by stulees**

### CODE REVIEW

**Comment by stulees** [comment]
@donnapep Please review, thanks

**Comment by donnapep** [comment]
@stulees Why does the version need that suffix?

**Comment by stulees** [comment]
@donnapep I want to pull in the latest code from master instead of my previous tagged version to use in widget-settings-ui-components. So in the bower of the widget-settings-ui-components repo, I'm omitting the tag at the end. But when I omit the tag it pulls in what the repo was prior to any of my commits to this repo. I'm not entirely sure why, so I think maybe it's because I didn't specify my own version and want to see if this corrects it.

**Comment by stulees** [comment]
@donnapep Also it should have the suffix anyway to be consistent with tagged versions I create.

**Comment by donnapep** [comment]
@stulees Your first tagged version should actually be 3.0.12. It shouldn't have the same version number as a previous release, even with the suffix appended. We do need to standardize on whether or not to use that suffix though, and I just looked at some of our other forked repos and some don't use it, but most do. So I think we're fine to standardize on using it.

**Comment by stulees** [comment]
@donnapep Yes, should have bumped the version prior to creating the tag, missed that. Fortunately, no source code that pertains to how the component works was modified for that tag, so pointing to it for the purpose of using the component without Background Settings changes still stands okay.

I've bumped the version and rebased. Thanks

**Comment by donnapep** [comment]
@stulees Sorry, one more thing I just thought of. Should there be a bump task added to the gulpfile? I'm OK with you adding this in later. :+1:

**Comment by stulees** [comment]
@donnapep Okay I'll make sure this gets added in the next PR, thanks

**Pull request merged**
