### PR TITLE
Merge remote branch upstream/master into chore/update

### PR DESCRIPTION
**Pull request by stulees**
- merging upstream remote branch 'master' to get latest updates including a necessary fix from this commit - https://goo.gl/LEYhHH
- bumping version

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi Please review, thanks

**Comment by rodrigopavezi** [comment]
@stulees looks good :+1: . Curious, is the code in this repo the same as the upstream repo? cheers

**Comment by stulees** [comment]
@rodrigopavezi I made sure I resolved conflicts when I did the merge, so the commits are all from upstream (forked) repo master branch but still maintains our code too.

**Comment by rodrigopavezi** [comment]
@stulees cool, thanks for the clarification.

**Pull request merged**
